# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 
  config.vm.box = "generic/centos8"
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  config.vm.network "public_network"
  config.vm.synced_folder "./jsp", "/home/vagrant/jsp"
  config.vm.provision "shell", inline: <<-SHELL
  #설치
	sudo yum update -y
	sudo yum install java-1.8.0-openjdk.x86_64 -y
	wget http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.27/bin/apache-tomcat-8.5.27.tar.gz
	tar zxvf apache-tomcat-8.5.27.tar.gz
	sudo mv apache-tomcat-8.5.27 /usr/local/tomcat8

	#환경변수
	JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.x86_64
	CATALINA_HOME=/usr/local/tomcat8
	CLASSPATH=$JAVA_HOME/jre/lib:$JAVA_HOME/lib/tools.jar:$CATALINA_HOME/lib-jsp-api.jar:$CATALINA_HOME/lib/servlet-api.jar
	PATH=$PATH:$JAVA_HOME/bin:/bin:/sbin
	export JAVA_HOME PATH CLASSPATH CATALINA_HOME
	
	
	#mysql connector 설치
	wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.28/mysql-connector-java-8.0.28.jar
	mv mysql-connector-java-8.0.28.jar /usr/local/tomcat8/lib/mysql-connector-java-8.0.28.jar

	#실행	
	sudo /usr/local/tomcat8/bin/startup.sh

	#방화벽
	sudo firewall-cmd --permanent --zone=public --add-port=8080/tcp
	sudo systemctl restart firewalld

	#index.jsp 이동
	mkdir /usr/local/tomcat8/webapps/test
	sudo cp /home/vagrant/jsp/index.jsp /usr/local/tomcat8/webapps/test/index.jsp
  SHELL
end
