# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
   config.vm.box = "generic/centos8"
   config.vm.network "forwarded_port", guest: 3306, host: 33066
   config.vm.network "public_network"
   config.vm.synced_folder "./sql", "/home/vagrant/sql"
   config.vm.provision "shell", inline: <<-SHELL
    #설치
    yum update -y
	yum install mysql-server -y
	
	#실행
	systemctl start mysqld
	
	#root@% 추가
	mysql -u root < /home/vagrant/sql/root.sql
	
	#방화벽
	firewall-cmd --permanent --zone=public --add-port=3306/tcp
	systemctl restart firewalld
	
	
  SHELL
end
