version: "3.7"

services:
  mysql:
    image: mysql
    container_name: db
    ports:
       - 33006:3306
    volumes:
      - empdb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql

volumes:
  empdb: