version: "3.7"

services:
  boot:
    image: boot05:v2
    build: .
    container_name: boot05
    ports:
       - 8080:8080
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    ports:
      - 33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - empdb:/var/lib/mysql
      
volumes:
  empdb: