Vagrant.configure("2") do |config|  
  config.vm.box = "generic/centos8"
  config.vm.network "forwarded_port", guest: 27017, host: 2717
  config.vm.network "forwarded_port", guest: 10000, host: 10000
  config.vm.network "forwarded_port", guest: 20000, host: 20000
  config.vm.network "forwarded_port", guest: 30000, host: 30000
 end
