version: "3.7"

services:
  app:
    image: node:12-alpine
    container_name: test
    command: sh -c "npm install -g express-generator@4 && express /tmp/foo && cd /tmp/foo && npm install && npm start"
    ports:
       - 3000:3000